### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by GiggliG** [andburn/hdt-plugin-statsconverter#1]
This doesn't seem to work with the latest HDT. Are you planning on updating it?

**Comment by andburn** [comment]
Thanks for letting me know. I'll get it fixed ASAP.

**Comment by andburn** [comment]
So, eventually got around to fixing this and improving it. New download [here](https://github.com/andburn/hdt-plugin-statsconverter/releases).
Also, some instructions on front page [Readme](https://github.com/andburn/hdt-plugin-statsconverter).
Let me know if there's any problems.

**Comment by GiggliG** [comment]
Great! It worked.
