### ISSUE TITLE
when i open the csv file ,it's garbled

### ISSUE THREAD

**Issue by chucklu** [andburn/hdt-plugin-statsconverter#10]
http://www.myintervals.com/forum/discussion/280/making-csv-data-exports-with-utf8-more-excel-friendly/
Handle data exports the way Google does: provide both a UTF8 and UTF16LE (Google calls it "CSV" and "CSV for Excel") download option.

Maybe consider this?

**Comment by chucklu** [comment]
when i open the csv file with notepad++
it's correct,like this:
Arena 02-01 04:54,v1.0,Mage,Arena,CHINA,-,2016-01-10 03:52:40,No,Paladin,暗夜之骑士,8,5,Loss,No,

when i open the csv file with Excel,it's 
鏆楀涔嬮獞澹?8

this is for 暗夜之骑士 in Chinese

**Comment by andburn** [comment]
I'll see if an option for this can be added.

**Comment by andburn** [comment]
I had a look at this and the UTF16LE format brings its own problems.

There is a solution, when you import the csv into Excel choose UTF8 in the options, see [this video](https://www.youtube.com/watch?v=GcYt1mJbwk4). It should display properly then.

**Comment by chucklu** [comment]
I know another method,open the csv with notepad
then save as ,set the encoding to ansi

it's not convenient
