### ISSUE TITLE
Not exporting brawl stats

### ISSUE THREAD

**Issue by GiggliG** [andburn/hdt-plugin-statsconverter#11]
When you export stats you dont have the option of selecting brawl.

If you select All, it doesn't export all the brawl stats. At a cursory glance, it looks like games with no deck are not being exported.

**Comment by andburn** [comment]
I'll have a look at this, ~~hopefully update it before the Old Gods patch.~~

**Comment by andburn** [comment]
Eventually fixed this :smile:

**Comment by GiggliG** [comment]
Great!
