### ISSUE TITLE
Stats converter 0.2.3 not compatible with HDT 0.14.7.

### ISSUE THREAD

**Issue by magei00** [andburn/hdt-plugin-statsconverter#12]
Hey there.
I seem to be having problems with the newest release of HDT, when i try to export my stats this message pops up.

![stat_converter_error](https://cloud.githubusercontent.com/assets/16518454/14920089/18b3cf92-0e2c-11e6-8830-90db09d3d5b8.PNG)

**Comment by GiggliG** [comment]
When I try to export stats, the plugin gets disabled. I don't see an error message.
