### ISSUE TITLE
Export arena stats and deck lists to CSV

### ISSUE THREAD

**Issue by andburn** [andburn/hdt-plugin-statsconverter#13]
From https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2429

**Comment by LVPols** [comment]
This would be great, can't wait!

**Comment by andburn** [comment]
Added something along these lines, when the option is selected with Arena mode (see [Readme](https://github.com/andburn/hdt-plugin-statsconverter/blob/master/README.md)) it will export a second file containing the extra arena run data.
