### ISSUE TITLE
plz fix in clobber other language

### ISSUE THREAD

**Issue by sdbds** [andburn/hdt-plugin-statsconverter#15]
i use HDT with Chinese
and when i use this statsconverter to export show many clobber which use Chinese

**Comment by andburn** [comment]
If you could upload your deck stats it would help me a lot in fixing this.
They are in a file called `DeckStats.xml`, find it by pressing `Windows + R` and typing `%APPDATA%\HearthstoneDeckTracker` in the box.

**Comment by sdbds** [comment]
here 。https://mega.nz/#!BA5ljC5T!p5uUkZA_4Smr7SLDEV_mqaPQ_tULViZYj9yzobE3W-k
