### ISSUE TITLE
Export matches full stats

### ISSUE THREAD

**Issue by benjaminh** [andburn/hdt-plugin-statsconverter#18]
Hello there, is there a way to export full data from the matches recorded through HDT ?
This plugin "only" (which is already great) exports metadata about matches (duration, turns, result, class, opponent, etc.)  but not data about turns themselves (card played, turn duration, hand composition, etc.).

Do you have in mind some way to export such data ?

**Comment by andburn** [comment]
You can all this information if you use hsreplay, I guess you knew that already though :smile: 
You would have to do export the hsreplay files from the deck tracker and do more work on them to get all the information you want in a more accessible format.

I won't be adding this data to the plugin, sorry.
