### ISSUE TITLE
Request: Configurable Filename

### ISSUE THREAD

**Issue by GiggliG** [andburn/hdt-plugin-statsconverter#2]
The way I intend to use this is to have a second excel workbook, where i create a link to the csv and import the data.

If I could configure the file name to not have a date, and just be "HDT stats" or whatever, I can safely overwrite the old version, and the other workbook will continue working normally.

I can do this manually of course, but it would be nice if I didn't have to.

**Comment by andburn** [comment]
[Updated](https://github.com/andburn/hdt-plugin-statsconverter/releases/tag/v0.1.1) to allow you to customize the file naming.
