### ISSUE TITLE
can not find reference

### ISSUE THREAD

**Issue by chucklu** [andburn/hdt-plugin-statsconverter#5]
![image](https://cloud.githubusercontent.com/assets/3004057/11322675/b4649db8-9131-11e5-8a97-9631ea27107a.png)

**Comment by chucklu** [comment]
CsvHelper
HearthstoneDeckTracker
MahApps.Metro
Newtonsoft.Json

**Comment by chucklu** [comment]
I can find
CsvHelper
MahApps.Metro
Newtonsoft.Json

can not find  HearthstoneDeckTracker

**Comment by chucklu** [comment]
I already create a pull request，https://github.com/andburn/hdt-plugin-statsconverter/pull/6
add 3 references I can find to the project

**Comment by chucklu** [comment]
it has been a week ,so ,when you will fix this?

**Comment by andburn** [comment]
My apologies that this was not fixed sooner, but as it was only a minor issue effecting only those building the plugin from source it was not a high priority.
