### ISSUE TITLE
weird NuGet packages location

### ISSUE THREAD

**Issue by chucklu** [andburn/hdt-plugin-statsconverter#7]
it's weird that I have two packages under my solution.they are the same .
hdt-plugin-statsconverter\packages
hdt-plugin-statsconverter\StatsConverter\packages

you can check the reference path in 
hdt-plugin-statsconverter\StatsConverter\StatsConverter.csproj

packages\CsvHelper.2.13.0.0
..\packages\MahApps.Metro.1.1.2.0
..\packages\Newtonsoft.Json.6.0.8

**Comment by andburn** [comment]
That is strange, I'll check

**Comment by chucklu** [comment]
It has been 17 days
so,if you have time to check this issue?

**Comment by andburn** [comment]
Fixed now. You'll have to delete your extra packages folder at `hdt-plugin-statsconverter\StatsConverter\packages` manually or _git clone_ a fresh copy of the repo.
