### ISSUE TITLE
The tag 'EnumDescriptionConverter' does not exist

### ISSUE THREAD

**Issue by chucklu** [andburn/hdt-plugin-statsconverter#8]
1>------ Build started: Project: StatsConverter, Configuration: Debug Any CPU ------
1>D:\SourceCode\GitHub\hdt-plugin-statsconverter\StatsConverter\Controls\ImportDialog.xaml(19,14): error MC3074: The tag 'EnumDescriptionConverter' does not exist in XML namespace 'clr-namespace:Hearthstone_Deck_Tracker.Enums;assembly=HearthstoneDeckTracker'. Line 19 Position 14.
1>D:\SourceCode\GitHub\hdt-plugin-statsconverter\StatsConverter\Controls\ExportDialog.xaml(19,14): error MC3074: The tag 'EnumDescriptionConverter' does not exist in XML namespace 'clr-namespace:Hearthstone_Deck_Tracker.Enums;assembly=HearthstoneDeckTracker'. Line 19 Position 14.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by chucklu** [comment]
but HDT always has to be added manually.
so,what is  the version of HDT.exe?

**Comment by andburn** [comment]
Not sure what causes this. It doesn't happen when you build HDT from source code using the **Debug** setting, and add a reference to that debug HDT.exe

**Comment by chucklu** [comment]
ok,I compiled the latest HDT,then it works.
