### ISSUE TITLE
Running StatsConverterTest corrupts PlayerDecks.xml

### ISSUE THREAD

**Issue by chucklu** [andburn/hdt-plugin-statsconverter#9]
since the test project is a dll,how can i do the test？

**Comment by andburn** [comment]
The tests can be run in Visual Studio
https://msdn.microsoft.com/en-us/library/ms182470.aspx

**Comment by chucklu** [comment]
run unit test?

**Comment by andburn** [comment]
I use the test explorer > run all
see here https://msdn.microsoft.com/en-us/library/ms182470.aspx#RunTestsFromUnitTestExplorer

**Comment by chucklu** [comment]
can not pass this test

[TestMethod]
        public void TestCsvHelper()
        {
            var exporter = new CSVExporter();
            var filter = new StatsFilter();
            var file = "sample-export.csv";
            exporter.To(file, filter.Apply(stats));
            var count = TestHelper.CountLines(file);
            Assert.AreEqual(10, count);
        }

I get this 
throw new Exception("PlayerDecks.xml is corrupted.");

**Comment by chucklu** [comment]
actually,my PlayerDecks.xml is not corrupted before I run the test
after I run the test,then my PlayerDecks.xml is broken

**Comment by chucklu** [comment]
it‘s confused,why the test will corrupt my PlayerDecks.xml?

**Comment by andburn** [comment]
Sorry, I don't know. The plugin doesn't access any of those files directly, it uses HDT functions to get the information. There should be a backup of your PlayerDecks.xml in %AppData%\HearthstoneDeckTracker

**Comment by chucklu** [comment]
yeah,i can find the backup
however,everytime i run the test
then it broke the playerdecks.xml,make it corrupted

**Comment by andburn** [comment]
Ok, I'll look into it.

**Comment by andburn** [comment]
I have tried to reproduce this but haven't been able to. I've no idea how this could be causing it, because the tests don't even access that file.
All, I can say is don't run the tests if this keeps happening.
